"""update remote model with new fields

Revision ID: 157cc023a777
Revises: 97bdad241461
Create Date: 2025-10-02 09:26:10.601520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '157cc023a777'
down_revision: Union[str, Sequence[str], None] = '97bdad241461'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('remotes', sa.Column('site_id_poi', sa.String(length=255), nullable=True))
    op.add_column('remotes', sa.Column('site_name', sa.String(length=255), nullable=False))
    op.add_column('remotes', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('remotes', sa.Column('origin_backbone', sa.String(length=255), nullable=True))
    op.add_column('remotes', sa.Column('origin_bb', sa.String(length=255), nullable=True))
    op.add_column('remotes', sa.Column('terminating_bb', sa.String(length=255), nullable=True))
    op.add_column('remotes', sa.Column('link', sa.String(length=255), nullable=True))
    op.add_column('remotes', sa.Column('jumlah_bts', sa.Integer(), nullable=True))
    op.add_column('remotes', sa.Column('bw', sa.String(length=255), nullable=True))
    op.add_column('remotes', sa.Column('vlan', sa.String(length=255), nullable=True))
    op.drop_index(op.f('ix_remotes_name'), table_name='remotes')
    op.create_index(op.f('ix_remotes_site_id_poi'), 'remotes', ['site_id_poi'], unique=False)
    op.create_index(op.f('ix_remotes_site_name'), 'remotes', ['site_name'], unique=False)
    op.drop_column('remotes', 'description')
    op.drop_column('remotes', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('remotes', sa.Column('name', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('remotes', sa.Column('description', mysql.TEXT(), nullable=True))
    op.drop_index(op.f('ix_remotes_site_name'), table_name='remotes')
    op.drop_index(op.f('ix_remotes_site_id_poi'), table_name='remotes')
    op.create_index(op.f('ix_remotes_name'), 'remotes', ['name'], unique=False)
    op.drop_column('remotes', 'vlan')
    op.drop_column('remotes', 'bw')
    op.drop_column('remotes', 'jumlah_bts')
    op.drop_column('remotes', 'link')
    op.drop_column('remotes', 'terminating_bb')
    op.drop_column('remotes', 'origin_bb')
    op.drop_column('remotes', 'origin_backbone')
    op.drop_column('remotes', 'notes')
    op.drop_column('remotes', 'site_name')
    op.drop_column('remotes', 'site_id_poi')
    # ### end Alembic commands ###
