"""Add reporter_contact to tickets table

Revision ID: 3f959f7be849
Revises: 7bf1fd6416fe
Create Date: 2025-10-01 12:43:02.458869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f959f7be849'
down_revision: Union[str, Sequence[str], None] = '7bf1fd6416fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('reporter_contact', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'reporter_contact')
    # ### end Alembic commands ###
