"""Add cascade delete for ticket actions

Revision ID: 7bf1fd6416fe
Revises: bad821b72487
Create Date: 2025-10-01 12:26:44.605926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bf1fd6416fe'
down_revision: Union[str, Sequence[str], None] = 'bad821b72487'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ticket_actions_ibfk_2'), 'ticket_actions', type_='foreignkey')
    op.create_foreign_key(None, 'ticket_actions', 'tickets', ['ticket_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ticket_actions', type_='foreignkey')
    op.create_foreign_key(op.f('ticket_actions_ibfk_2'), 'ticket_actions', 'tickets', ['ticket_id'], ['id'])
    # ### end Alembic commands ###
