"""Add Remote model

Revision ID: 97bdad241461
Revises: 3f959f7be849
Create Date: 2025-10-01 20:53:05.478488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97bdad241461'
down_revision: Union[str, Sequence[str], None] = '3f959f7be849'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remotes_id'), 'remotes', ['id'], unique=False)
    op.create_index(op.f('ix_remotes_name'), 'remotes', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_remotes_name'), table_name='remotes')
    op.drop_index(op.f('ix_remotes_id'), table_name='remotes')
    op.drop_table('remotes')
    # ### end Alembic commands ###
